node1:
  build: .
  volumes:
    - "./app:/src/app"
  ports:
    - "3031:3000"
  links:
    - "db:redis"

node2:
  build: .
  volumes:
    - "./app:/src/app"
  ports:
    - "3032:3000"
  links:
    - "db:redis"

db:
  image: redis